/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from './dashboard.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '@angular/router';
import * as import3 from '@angular/common';
import * as import4 from '../../../src/app/dashboard.component';
import * as import5 from '../../../src/app/hero.service';
const styles_DashboardComponent:any[] = [import0.styles];
export const RenderType_DashboardComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_DashboardComponent,
  data: {}
}
);
function View_DashboardComponent_1(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
      (l()(),import1.ɵeld(0,(null as any),(null as any),9,'a',[[
        'class',
        'col-1-4'
      ]
    ],[
      [
        1,
        'target',
        0
      ]
      ,
      [
        8,
        'href',
        4
      ]

    ]
      ,[[
        (null as any),
        'click'
      ]
    ],(v,en,$event) => {
      var ad:boolean = true;
      if (('click' === en)) {
        const pd_0:any = ((<any>import1.ɵnov(v,1).onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
        ad = (pd_0 && ad);
      }
      return ad;
    },(null as any),(null as any))),
    import1.ɵdid(335872,(null as any),0,import2.RouterLinkWithHref,[
      import2.Router,
      import2.ActivatedRoute,
      import3.LocationStrategy
    ]
      ,{routerLink: [
        0,
        'routerLink'
      ]
    },(null as any)),
    import1.ɵpad(2),
    (l()(),import1.ɵted((null as any),['\n    '])),
      (l()(),import1.ɵeld(0,(null as any),(null as any),4,'div',[[
        'class',
        'module hero'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n      '])),
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'h4',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),[
      '',
      ''
    ]
    )),
    (l()(),import1.ɵted((null as any),['\n    '])),
    (l()(),import1.ɵted((null as any),['\n  ']))
  ]
  ,(ck,v) => {
    const currVal_2:any = ck(v,2,0,'/detail',v.context.$implicit.id);
    ck(v,1,0,currVal_2);
  },(ck,v) => {
    const currVal_0:any = import1.ɵnov(v,1).target;
    const currVal_1:any = import1.ɵnov(v,1).href;
    ck(v,0,0,currVal_0,currVal_1);
    const currVal_3:any = v.context.$implicit.name;
    ck(v,7,0,currVal_3);
  });
}
export function View_DashboardComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'h3',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['Top Heroes'])),
    (l()(),import1.ɵted((null as any),['\n'])),
      (l()(),import1.ɵeld(0,(null as any),(null as any),4,'div',[[
        'class',
        'grid grid-pad'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n  '])),
    (l()(),import1.ɵand(8388608,(null as any),(null as any),1,(null as any),View_DashboardComponent_1)),
    import1.ɵdid(401408,(null as any),0,import3.NgForOf,[
      import1.ViewContainerRef,
      import1.TemplateRef,
      import1.IterableDiffers
    ]
      ,{ngForOf: [
        0,
        'ngForOf'
      ]
    },(null as any)),
    (l()(),import1.ɵted((null as any),['\n']))
  ]
  ,(ck,v) => {
    var co:import4.DashboardComponent = v.component;
    const currVal_0:any = co.heroes;
    ck(v,6,0,currVal_0);
  },(null as any));
}
function View_DashboardComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'my-dashboard',([] as any[]),(null as any),(null as any),(null as any),View_DashboardComponent_0,RenderType_DashboardComponent)),
    import1.ɵdid(57344,(null as any),0,import4.DashboardComponent,[import5.HeroService],(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const DashboardComponentNgFactory:import1.ComponentFactory<import4.DashboardComponent> = import1.ɵccf('my-dashboard',import4.DashboardComponent,View_DashboardComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1ZvbHVtZXMvSEREL3dvcmsvQ2xpZW50IFdvcmsvVGhlUnVsZXMvRGV2L3RoZS1ydWxlcy9zcmMvYXBwL2Rhc2hib2FyZC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVm9sdW1lcy9IREQvd29yay9DbGllbnQgV29yay9UaGVSdWxlcy9EZXYvdGhlLXJ1bGVzL3NyYy9hcHAvZGFzaGJvYXJkLmNvbXBvbmVudC50cyIsIm5nOi8vL1ZvbHVtZXMvSEREL3dvcmsvQ2xpZW50IFdvcmsvVGhlUnVsZXMvRGV2L3RoZS1ydWxlcy9zcmMvYXBwL2Rhc2hib2FyZC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1ZvbHVtZXMvSEREL3dvcmsvQ2xpZW50IFdvcmsvVGhlUnVsZXMvRGV2L3RoZS1ydWxlcy9zcmMvYXBwL2Rhc2hib2FyZC5jb21wb25lbnQudHMuRGFzaGJvYXJkQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGgzPlRvcCBIZXJvZXM8L2gzPlxuPGRpdiBjbGFzcz1cImdyaWQgZ3JpZC1wYWRcIj5cbiAgPGEgKm5nRm9yPVwibGV0IGhlcm8gb2YgaGVyb2VzXCIgIFtyb3V0ZXJMaW5rXT1cIlsnL2RldGFpbCcsIGhlcm8uaWRdXCIgIGNsYXNzPVwiY29sLTEtNFwiPlxuICAgIDxkaXYgY2xhc3M9XCJtb2R1bGUgaGVyb1wiPlxuICAgICAgPGg0Pnt7aGVyby5uYW1lfX08L2g0PlxuICAgIDwvZGl2PlxuICA8L2E+XG48L2Rpdj4iLCI8bXktZGFzaGJvYXJkPjwvbXktZGFzaGJvYXJkPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O01DRUU7UUFBQTtRQUFBO01BQUE7SUFBQTtNQUFBO1FBQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO1FBQUE7TUFBQTs7SUFBQTtPQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7TUFBQTtNQUFBO1FBQUE7UUFBQTtNQUFBO01BQUE7SUFBQTtnQkFBQTs7OztJQUFBO09BQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtnQkFBZ0M7SUFBcUQ7TUFDbkY7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUF5QjtJQUN2QjtJQUFJO01BQUE7TUFBQTtJQUFBO0lBQUE7SUFBa0I7SUFDbEI7OztJQUh3QjtJQUFoQyxTQUFnQyxTQUFoQzs7SUFBQTtJQUFBO0lBQUEsU0FBQSxtQkFBQTtJQUVRO0lBQUE7Ozs7O0lBSlY7SUFBSTtJQUFlO01BQ25CO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBMkI7SUFDekI7Z0JBQUE7Ozs7SUFBQTtPQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFJSTs7OztJQUpEO0lBQUgsU0FBRyxTQUFIOzs7OztJQ0ZGO2dCQUFBOzs7SUFBQTs7OyJ9
